project:
  type: website
  output-dir: docs
  resources:
    - favicon-delta.ico
    - loss-surface-between-banners.js

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-after-body: background.html

website:
  title: "Samantha Magid"
  site-url: "https://magid.systems"
  favicon: favicon-delta.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV

    right:
      - icon: github
        href: https://github.com/crabwife

  page-footer:
    border: true
    left: "© 2026 Samantha Magid"
    center: "[Vermont Complex Systems Institute](https://vermontcomplexsystems.org/)"
    right: "[Email](mailto:samantha.magid@uvm.edu) · [ORCID](https://orcid.org/0009-0004-0358-4870) · [GitHub](https://github.com/crabwife) · [CV](cv.html) · [Writing](https://sefermiriam.substack.com/)"
